name: Publish Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # 3. Setup Node.js (requerido por Playwright)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 4. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore UPTSiteTests/UPTSiteTests.csproj

      # 5. Build project
      - name: Build solution
        run: dotnet build UPTSiteTests/UPTSiteTests.csproj --configuration Debug --no-restore

      # 6. Instalar navegadores de Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 7. Ejecutar tests con cobertura
      - name: Run tests with code coverage
        run: dotnet test UPTSiteTests/UPTSiteTests.csproj --collect:"XPlat Code Coverage" --results-directory TestResults

      # 8. Instalar ReportGenerator
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      # 9. Generar reporte HTML
      - name: Generate HTML report
        run: reportgenerator "-reports:TestResults/**/coverage.cobertura.xml" "-targetdir:Cobertura" -reporttypes:HTML

      # 10. Verificar carpeta Cobertura
      - name: List Coverage Folder
        run: ls -la Cobertura

      # 11. Configurar GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 12. Subir reporte a Pages
      - name: Upload Coverage Report
        uses: actions/upload-pages-artifact@v3
        with:
          path: Cobertura

      # 13. Deploy en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
